apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.environment }}
    app.kubernetes.io/part-of: devsecops-demo
    app.kubernetes.io/managed-by: {{ .Release.Service }}
